//TIMES
export const SET_PRAYER_TIMES = "SET_PRAYER_TIMES";
export const SET_SUNNAH_TIMES = "SET_SUNNAH_TIMES";
export const SET_CURRENT_PRAYER = "SET_CURRENT_PRAYER";
// export const SET_CURRENT_PRAYER_TIME = "SET_CURRENT_PRAYER_TIME";
// export const SET_NEXT_PRAYER = "SET_NEXT_PRAYER";
// export const SET_NEXT_PRAYER_TIME = "SET_NEXT_PRAYER_TIME";

//LOCATION
export const SET_LOCATION = "SET_LOCATION";
